# Generated by Django 4.0.6 on 2022-07-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Numero da planilha')),
                ('evento', models.CharField(max_length=50)),
                ('pontuacao_maxima', models.PositiveIntegerField(default=3)),
                ('data_evento', models.DateTimeField(verbose_name='data rodizio')),
                ('dia_semana', models.CharField(choices=[('---', '---'), ('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], default='---', max_length=50, verbose_name='Dia da Semana')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rodizio',
                'ordering': ('numero',),
            },
        ),
    ]
