# Generated by Django 4.0.6 on 2022-07-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaqueiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=25, unique=True)),
                ('telefone', models.CharField(max_length=30)),
                ('nome_guerra', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
