# Generated by Django 4.0.6 on 2022-07-30 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.CharField(max_length=10)),
                ('vaqueiro', models.CharField(max_length=40)),
                ('primeiro_boi', models.CharField(blank=True, choices=[('---', '---'), ('Valeu boi', 'Valeu boi'), ('0', '0'), ('R', 'R'), ('D', 'D')], default='---', max_length=50, null=True, verbose_name='1° Boi')),
                ('hora_p', models.TimeField(blank=True, null=True, verbose_name='hora')),
                ('segundo_boi', models.CharField(blank=True, choices=[('---', '---'), ('Valeu boi', 'Valeu boi'), ('0', '0'), ('R', 'R'), ('D', 'D')], default='---', max_length=50, null=True, verbose_name='2° Boi')),
                ('hora_s', models.TimeField(blank=True, null=True, verbose_name='hora')),
                ('terceiro_boi', models.CharField(blank=True, choices=[('---', '---'), ('Valeu boi', 'Valeu boi'), ('0', '0'), ('R', 'R'), ('D', 'D')], default='---', max_length=50, null=True, verbose_name='3° Boi')),
                ('hora_t', models.TimeField(blank=True, null=True, verbose_name='hora')),
                ('quarto_boi', models.CharField(blank=True, choices=[('---', '---'), ('Valeu boi', 'Valeu boi'), ('0', '0'), ('R', 'R'), ('D', 'D')], default='---', max_length=50, null=True, verbose_name='4° Boi')),
                ('hora_q', models.TimeField(blank=True, null=True, verbose_name='hora')),
                ('quinto_boi', models.CharField(blank=True, choices=[('---', '---'), ('Valeu boi', 'Valeu boi'), ('0', '0'), ('R', 'R'), ('D', 'D')], default='---', max_length=50, null=True, verbose_name='5° Boi')),
                ('hora_qt', models.TimeField(blank=True, null=True, verbose_name='hora')),
                ('sexto_boi', models.CharField(blank=True, choices=[('---', '---'), ('Valeu boi', 'Valeu boi'), ('0', '0'), ('R', 'R'), ('D', 'D')], default='---', max_length=50, null=True, verbose_name='6° Boi')),
                ('hora_sx', models.TimeField(blank=True, null=True, verbose_name='hora')),
                ('setimo_boi', models.CharField(blank=True, choices=[('---', '---'), ('Valeu boi', 'Valeu boi'), ('0', '0'), ('R', 'R'), ('D', 'D')], default='---', max_length=50, null=True, verbose_name='7° Boi')),
                ('hora_st', models.TimeField(blank=True, null=True, verbose_name='hora')),
                ('oitavo_boi', models.CharField(blank=True, choices=[('---', '---'), ('Valeu boi', 'Valeu boi'), ('0', '0'), ('R', 'R'), ('D', 'D')], default='---', max_length=50, null=True, verbose_name='8° Boi')),
                ('hora_oitavo', models.TimeField(blank=True, null=True, verbose_name='hora')),
                ('conferida', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categoria.categoria')),
                ('eventos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Pontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_nome', models.CharField(max_length=80)),
                ('qtd', models.PositiveIntegerField(verbose_name='Total de pontos da categoria')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categoria.categoria')),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corrida.corrida')),
                ('eventos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.evento')),
            ],
        ),
    ]
