# Generated by Django 4.0.6 on 2022-07-30 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrida', models.IntegerField()),
                ('senha', models.CharField(blank=True, max_length=10, null=True)),
                ('vaqueiro', models.CharField(default='Vaqueiro', max_length=40)),
                ('ativa', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categoria.categoria')),
                ('eventos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.evento')),
            ],
        ),
    ]
